name: google_maps_pick_place
description: A pub.dev package which helps pick a location from google maps
version: 0.8.7
homepage: https://github.com/youssufhebish/google_maps_pick_place

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  permission_handler: ^11.0.0
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
